apiVersion: v1
kind: ConfigMap
metadata:
  name: etcd-configmap
  namespace: default
data:
  conf.yaml: |-
    ad_identifiers:
      - etcd
    init_config:
    instances:
      - use_preview: true
        prometheus_url: https://%%host%%:2379/metrics
        ssl_cert: /etc/kubernetes/pki/etcd/peer.crt
        ssl_private_key: /etc/kubernetes/pki/etcd/peer.key
        ssl_ca_cert: /etc/kubernetes/pki/etcd/ca.crt
