apiVersion: v1
kind: ConfigMap
metadata:
  name: snmp-configmap
  namespace: default
data:
  conf.yaml: |-
    init_config:
      mibs_folder: /use/share/snmp/mibs
    instances:
      - ip_address: 192.168.1.249
        port: 161
        community_string: th0m@t0s
        retries: 3
        metrics:
          - MIB: UDP-MIB
            symbol: udpInDatagrams
          - MIB: TCP-MIB
            symbol: tcpActiveOpens
          - OID: 1.3.6.1.2.1.6.5
            name: tcpPassiveOpens
          - OID: 1.3.6.1.2.1.6.5
            name: tcpPassiveOpens
            metric_tags:
              - TCP
          - MIB: IF-MIB
            table: ifTable
            symbols:
              - ifInOctets
              - ifOutOctets
            metric_tags:
              - tag: interface
                column: ifDescr
